version: '2'
services:
  mysql:
    image: mysql:5.7.15
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWD
      MYSQL_DATABASE: piwik
      MYSQL_USER: piwik
      MYSQL_PASSWORD: $MYSQL_PIWIK_PASSWD
  piwik:
    build: ./docker-piwik
    image: piwik:latest
    ports:
      - "9000:9000"
    depends-on:
      - mysql

